apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: copilot-ingress
  namespace: projects
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-issuer
spec:
  ingressClassName: nginx
  tls:
  - hosts: 
    - copilot.alexmickelson.guru
    secretName: copilot-tls-cert
  rules:
  - host: copilot.alexmickelson.guru
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: copilot-service
            port:
              number: 4444
---
apiVersion: v1
kind: Service
metadata:
  name: copilot-service
  namespace: projects
spec:
  type: ExternalName
  externalName: 100.122.128.107
