services:
  yubal:
    image: ghcr.io/guillevc/yubal:latest
    container_name: yubal
    ports:
      - 5555:8000
    environment:
      YUBAL_TZ: UTC
    volumes:
      - /data/media/music/tagged:/app/data # Where your music will be saved
      - /data/yubal/beets:/app/beets # Beets configuration and database
      - /data/yubal/ytdlp:/app/ytdlp # yt-dlp configuration (cookies)
    restart: unless-stopped